config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  get "/agreement", to: "static_pages#agreement"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users do
    member do
      get :following, :followers, :favorites, :change_password, :more_favorites, :more_microposts
    end
  end

  get "/login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get 'password_resets/new'
  get 'password_resets/edit'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :microposts do
    member do
      post :favorite
    end
  end

  resources :comments, only: :create
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :notifications, only: :index

  get '/auth/:provider/callback', to: 'users#facebook_login', as: :auth_callback

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :favorite_user, class_name: "User"
  belongs_to :favorite_post, class_name: "Micropost"

  validates :favorite_user_id, presence: true
  validates :favorite_post_id, presence: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :logged_in_user

  def create
    @micropost = Micropost.find(params[:post_id])
    current_user.favorite(@micropost)
    @user = @micropost.user
    @user.notifications.create(notified_by_id: current_user.id,
                        micropost_id: @micropost.id, notification_type: "favorite")
    respond_to do |format|
      format.html {redirect_back(fallback_location: root_path)}
      format.js
    end
  end

  def destroy
    @micropost = Favorite.find(params[:id]).favorite_post
    current_user.unfavorite(@micropost)
    respond_to do |format|
      format.html {redirect_back(fallback_location: root_path)}
      format.js
    end
  end

end

app/views/favorites/create.js.erb
<% micropost = @micropost %>
$("#micropost-<%= micropost.id %>").children("#favorite_btn").html('<%= link_to fa_icon("star 2x yellow"), favorite_path(Favorite.find_by(favorite_post_id: micropost.id)), method: :delete, remote: true %>');

if ($('#user_id').val() == null || $('#user_id').val() * 1 == <%= current_user.id %>) {
  // 自分のページ
  $("#favorites").html('<%= current_user.favorite_posts.count %>')
} else {
  // 他人のページをレンダーしてるときは何もしない
  ;
};

$('#micropost-<%= micropost.id %>').children('#favorites-count').html('お気に入り <%= micropost.favorite_users.count %>件')

app/views/favorites/destroy.js.erb
<% micropost = @micropost %>
$("#micropost-<%= micropost.id %>").children("#favorite_btn").html('<%= link_to fa_icon("star 2x light-gray"), favorites_path(params: {post_id: micropost.id}),method: :post, remote: true %>');

if ($('#user_id').val() == null || $('#user_id').val() * 1 == <%= current_user.id %>) {
  // 自分のページ
  $("#favorites").html('<%= current_user.favorite_posts.count %>')
} else {
  // 他人のページをレンダーしてるときは何もしない
  ;
};

$('#micropost-<%= micropost.id %>').children('#favorites-count').html('お気に入り <%= micropost.favorite_users.count %>件')