config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  get "/agreement", to: "static_pages#agreement"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users do
    member do
      get :following, :followers, :favorites, :change_password, :more_favorites, :more_microposts
    end
  end

  get "/login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get 'password_resets/new'
  get 'password_resets/edit'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :microposts do
    member do
      post :favorite
    end
  end

  resources :comments, only: :create
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :notifications, only: :index

  get '/auth/:provider/callback', to: 'users#facebook_login', as: :auth_callback

end

app/models/user.rb
class User < ApplicationRecord

  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id",
                                   dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :favorites, foreign_key: "favorite_user_id", dependent: :destroy
  # user.favorites.map(&:favorite_post)と同じことを、has_many throughが行う
  has_many :favorite_posts, through: :favorites, source: :favorite_post

  has_many :notifications, dependent: :destroy
  has_many :notified_to, class_name: "Notification", foreign_key: "notified_by_id",
                         dependent: :destroy

  attr_accessor :remember_token, :activation_token, :reset_token

  before_save :email_downcase
  before_create :creat_activation_digest

  validates :name, presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: {case_sensitive: false},
                    length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX}

  has_secure_password

  validates :password, presence: true, length: {minimum: 6}, allow_nil: true


  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids}) OR user_id = (:user_id)",
                    user_id: id)
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def favorite(post)
    favorite_posts << post
  end

  def unfavorite(post)
    favorites.find_by(favorite_post_id: post.id).destroy
  end

  def favorite?(post)
    favorite_posts.include?(post)
  end

  def has_unread_notifications?
    notifications.where(read: false).any?
  end

  class << self

    def from_omniauth(auth)
      # facebookの登録emailでuserを取得する
      user = User.where(email: auth.info.email).first

      if user.nil?
        user = User.new
      end

      # facebookログインではパスワードを取得できないため、ダミーを生成
      password_dummy = SecureRandom.hex(8)
      user.password = password_dummy
      user.password_confirmation = password_dummy

      user.uid   = auth.uid
      user.provider = auth.provider
      user.name  = auth.info.name
      user.email = auth.info.email
      user.oauth_token      = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)

      user

    end

    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  private

    def email_downcase
      self.email.downcase!
    end

    def creat_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update, :index, :destroy,
                                        :following, :followers, :favorites, :change_password]
  before_action :correct_user, only: [:edit, :update, :change_password]
  before_action :correct_user_or_admin_user, only: :destroy

  def new
  end

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find_by(id: params[:id])
    @microposts = @user.microposts.where.not(picture: nil).paginate(page: params[:microposts_page], per_page: 6)
    @favorites = @user.favorite_posts.paginate(page: params[:favorites_page], per_page: 20)
    redirect_to root_url and return unless @user.activated
    @comment = current_user.comments.build
  end

  def more_microposts
    @user = User.find_by(id: params[:id])
    @microposts = @user.microposts.where.not(picture: nil).paginate(page: params[:microposts_page], per_page: 6)
    @favorites = @user.favorite_posts.paginate(page: params[:favorites_page], per_page: 20)
    @comment = current_user.comments.build
  end

  def more_favorites
    @user = User.find_by(id: params[:id])
    @microposts = @user.microposts.where.not(picture: nil).paginate(page: params[:microposts_page], per_page: 6)
    @favorites = @user.favorite_posts.paginate(page: params[:favorites_page], per_page: 20)
    @comment = current_user.comments.build
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @user.send_activation_email
      flash[:info] = "送信されたメールからアカウントを有効化してください。"
      redirect_to root_url
    else
      render "new"
    end

  end

  def edit
    @page_title = "プロフィールの編集"
    @partial = "edit_form"
  end

  def update

    if params[:origin_form] == "change_password"
      if params[:user][:password].blank?
        flash.now[:danger] = "パスワードを入力してください"
        @partial = "change_password_form"
        render "edit"
        return
      end
    end

    if @user.update_attributes(user_params)
      flash[:success] = "変更を保存しました"
      redirect_to @user
    else
      if params[:origin_form] == "edit"
        @partial = "edit_form"
      else
        @partial = "change_password_form"
      end
      render "edit"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "アカウントを削除しました"
    redirect_to root_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render "show_follow"
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render "show_follow"
  end

  def favorites
    @user = User.find(params[:id])
    @microposts = @user.favorite_posts.paginate(page: params[:page])
    @comment = current_user.comments.build
  end

  def change_password
    @page_title = "パスワードの変更"
    @partial = "change_password_form"
    render "edit"
  end

  def facebook_login

    facebook_params = request.env["omniauth.auth"]

    @user = User.from_omniauth(facebook_params)
    if @user.save
      log_in @user
      @user.activate
      remember(@user)
      flash[:success] = "Facebookアカウントでログインしました"
      redirect_to @user
    else
      flash[:danger] = "Facebookアカウントでのログインに失敗しました"
      redirect_to auth_failure_path
    end

  end

  private

    def user_params
      params.require(:user).permit(:full_name, :name, :email, :password,
                                   :password_confirmation, :website,
                                   :self_introduction, :telephone_number,
                                   :gender)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def correct_user_or_admin_user
      @user = User.find(params[:id])
      if !current_user.admin? && !current_user?(@user)
        redirect_to root_url
      end
    end


end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size: 100)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_edit_form.html.erb
<div class="gravatar_edit">
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails" target="_blank" rel="noopener">プロフィール画像を変更する</a>
</div>

<div class="edit-form">
  <%= form_for(@user, url: yield(:path)) do |f| %>
    <%= render "shared/error_messages", object: f.object %>

    <%= hidden_field_tag :origin_form, :edit %>

    <%= f.label :full_name, "フルネーム" %>
    <%= f.text_field :full_name, class: "form-control" %>

    <%= f.label :name, "ユーザーネーム" %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :website, "ウェブサイト" %>
    <%= f.text_field :website, class: "form-control" %>

    <%= f.label :self_introduction, "自己紹介" %>
    <%= f.text_area :self_introduction, class: "form-control" %>

    <p>非公開情報</p>

    <%= f.label :email, "メールアドレス"%>
    <%= f.email_field :email, class: "form-control" %>

    <%= f.label :telephone_number, "電話番号" %>
    <%= f.text_field :telephone_number, class: "form-control" %>

    <%= f.label :gender, "性別" %>
    <%= f.select :gender, [["男性", "male"], ["女性", "female"]] %>

    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>

  <%= link_to("アカウントを削除する", @user, method: :delete,
      data: {confirm: "アカウントを削除してよろしいですか？"},
      class: "btn btn-danger") %>

</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>

  <div id="follow-form">
    <% if current_user.following?(@user) %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>

<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:path)) do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :full_name, "フルネーム" %>
  <%= f.text_field :full_name, class: "form-control" %>

  <%= f.label :name, "ユーザーネーム" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, "メールアドレス"%>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, "パスワード" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, "パスワードの確認" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_more_favorites_link.html.erb
<% if @favorites.next_page %>
  <%= link_to "もっと見る",
      more_favorites_user_path(@user, param_name: "favorites_page", favorites_page: @favorites.next_page),
      remote: true, onclick: "loading_favorites();", id: "more_favorites_link" %>
<% end %>

app/views/users/_more_microposts_link.html.erb
<% if @microposts.next_page %>
  <%= link_to "写真もっと見る",
      more_microposts_user_path(@user, param_name: "microposts_page", microposts_page: @microposts.next_page),
      remote: true, onclick: "loading_microposts();", id: "more_microposts_link" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: {method: :delete}, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-default" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  | <%= link_to("delete", user, method: :delete,
                 data: {confirm: "You sure?"}) %>
  <% end %>

</li>

app/views/users/edit.html.erb
<% provide(:title, "プロフィール編集") %>
<% provide(:button_text, "変更を保存する") %>
<% provide(:path, user_path) %>
<% provide(:partial, @partial) %>
<h1><%= @page_title %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= render "#{yield(:partial)}" %>

    <!-- <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div> -->

  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, "All users") %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/more_favorites.js.erb
$('#microposts').append("<% @favorites.each do |favorite_post| %>");
$('#microposts').append('<%= j(render "microposts/micropost", micropost:favorite_post) %>');
$('#microposts').append("<% end %>");
$('#more_favorites_link').replaceWith('<%= j(render "more_favorites_link") %>');

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<% provide(:button_text, "Create my account") %>
<% provide(:path, signup_path) %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= link_to("Facebookで登録する", "/auth/facebook") %>

    <%= render "form" %>

    <div class="agreement">
      <%= link_to("登録することで、Facebookの利用規約、データに関するポリシー、Cookieポリシーに同意するものとします。",
                   agreement_path) %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<%= hidden_field :user, :id %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="row user-profile">
      <div class="col-xs-4">
        <%= gravatar_for @user, size: 150 %>
      </div>

      <div class="col-xs-8">
        <section class="user-info">
          <h3><%= @user.name %></h3>
          <section>
            <%= render "shared/stats" %>
          </section>
          <% if current_user?(@user) %>
            <a href="<%= edit_user_path %>" class="btn btn-default">プロフィールを編集</a>
            <%= link_to "パスワードの変更", change_password_user_path(current_user), class: "btn btn-default" %>
          <% else %>
            <%= render "follow_form" if logged_in? %>
          <% end %>
          <div class="self-itroduction">
            <p><%= @user.full_name %></p>
            <p><%= @user.self_introduction %></p>
            <p><%= @user.website %></p>
          </div>
        </section>
      </div>
    </div>

    <!-- tab_menu -->
    <ul class="nav nav-tabs">
      <li class="nav-item active">
        <a href="#thumnails_tab" data-toggle="tab" class="nav-link">
          <%= "写真#{@user.microposts.where.not(picture: nil).count}件" %></a>
      </li>
      <li class="nav-item">
        <a href="#favorites_tab" data-toggle="tab" class="nav-link">
          <%= "#{@user.favorites.count}お気に入り" %></a>
      </li>
    </ul>

    <!-- tab_contents -->
    <div class="tab-content">

      <div class="row tab-pane active" id="thumnails_tab">
        <div id="thumnails">
          <% if @microposts.any? %>
          <div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
            <% @microposts.each do |micropost| %>
              <div class="col-xs-4">

                <%= link_to image_tag(micropost.picture.url, class: "thumnail"),
                    micropost_path(micropost), remote: true %>
              </div>
            <% end %>
          <% end %>
        </div>
        <%= render "more_microposts_link" %>
      </div>

      <div class="row tab-pane" id="favorites_tab">
        <div class="col-md-8 col-md-offset-2">
          <ol class="microposts" id="microposts">
            <% @favorites.each do |favorite_post| %>
              <%= render "microposts/micropost", micropost: favorite_post %>
            <% end %>
          </ol>
          <%= render "more_favorites_link" %>
        </div>
      </div>

    </div>

  </div>
</div>

<script type="text/javascript">
  function loading_favorites(){
    $("#more_favorites_link").replaceWith('<span id="more_favorites_link">Loading...</span>');
  };
</script>

<script type="text/javascript">
  function loading_microposts(){
    $("#more_microposts_link").replaceWith('<span id="more_microposts_link">Loading...</span>');
  };
</script>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>

<div class="row">
  <aside class="col-md-8 col-md-offset-2">

    <div class="row user-profile">
      <div class="col-xs-4">
        <%= gravatar_for @user, size: 150 %>
      </div>

      <div class="col-xs-8">
        <section class="user_info">
          <h3><%= @user.name %></h3>
          <span><%= link_to("View my profle", @user) %></span>
          <section>
            <%= render "shared/stats" %>
          </section>
        </section>
      </div>
    </div>

    <div class="col-md-6 col-md-offset-3">
      <h3><%= @title %></h3>
      <% if @users.any? %>
        <ul class="users follow">
          <%= render @users %>
        </ul>
      <% end %>
      <%= will_paginate %>
    </div>

  </aside>



</div>