config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  get "/agreement", to: "static_pages#agreement"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users do
    member do
      get :following, :followers, :favorites, :change_password, :more_favorites, :more_microposts
    end
  end

  get "/login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get 'password_resets/new'
  get 'password_resets/edit'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :microposts do
    member do
      post :favorite
    end
  end

  resources :comments, only: :create
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :notifications, only: :index

  get '/auth/:provider/callback', to: 'users#facebook_login', as: :auth_callback

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_home_login_user.html.erb
<div class="row">

  <div class="col-md-6 col-md-offset-3">
    <%= render "shared/feed" %>
  </div>

</div>

app/views/shared/_home_non_login_user.html.erb
<div class="center jumbotron top-page">
  <h1>Instagram_clone</h1>

  <h2>
    Instagram_cloneを始めましょう
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "投稿", class: "btn btn-primary" %>
  <span>
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $("#micropost_picture").bind("change", function(){
    var file_in_megabytes = self.files[0].size / 1024 / 1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <div>
    <span class="stat">
      <%= "投稿#{@user.microposts.count}件" %>
    </span>
  </div>
  <a href="<%= following_user_path(@user) %>">
    <span id="following" class="stat">
      <%= "#{@user.following.count}人をフォロー中" %>
    </span>
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <span id="followers" class="stat">
      <%= "フォロワー#{@user.followers.count}人"%>
    </span>
  </a>
  <a href="<%= favorites_user_path(@user) %>">
    <span id="favorites" class="stat">
      <%= "#{@user.favorites.count}お気に入り" %>
    </span>
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 150), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "View my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>