config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  get "/agreement", to: "static_pages#agreement"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users do
    member do
      get :following, :followers, :favorites, :change_password, :more_favorites, :more_microposts
    end
  end

  get "/login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get 'password_resets/new'
  get 'password_resets/edit'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :microposts do
    member do
      post :favorite
    end
  end

  resources :comments, only: :create
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :notifications, only: :index

  get '/auth/:provider/callback', to: 'users#facebook_login', as: :auth_callback

end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <ul class="nav navbar-nav">
      <li>
        <%= link_to fa_icon("home 2x"), root_path %>
      </li>
      <% if logged_in? %>
        <li>
          <%= link_to fa_icon("plus-square 2x"), new_micropost_path %>
        </li>
        <li>
          <%= link_to fa_icon("user 2x"), user_path(current_user) %>
      </li>
      <% end %>
    </ul>
  </div>
</footer>

app/views/layouts/_head.html.erb
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>

<%= stylesheet_link_tag 'application', media: 'all',
                        'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application',
                           'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to fa_icon("camera-retro 3x white"), root_path %>
    <%= link_to "Instagram_clone", root_path, id: "logo" %>

      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>

          <li>
            <%= form_tag(microposts_path, method: :get, class: "navbar-form") do %>
              <div class="form-group">
                <%= text_field_tag :search, '', class: "form-control" %>
              </div>
                <%= button_tag "検索", type: "submit", name: nil, class: "btn btn-default" %>
            <% end %>
          </li>

          <li>
            <% if current_user.has_unread_notifications? %>
                <a href="<%= notifications_path %>">
                  <i class="fa fa-bell fa-yellow" id="fa-bell"></i>
                  <%= current_user.notifications.where(read: false).count %>
                </a>
            <% else %>
                <a href="<%= notifications_path %>">
                  <i class="fa fa-bell" id="fa-bell"></i>
                </a>
                <!-- <%= link_to fa_icon("bell"), notifications_path %> -->
            <% end %>
          </li>

          <li><%= link_to "ユーザー一覧", users_path %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "自分のプロフィール", user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>

        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>

  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>